# Generated by Django 4.1.6 on 2023-03-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Murojat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('emel', models.CharField(max_length=30)),
                ('sub', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=30)),
                ('data', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
